apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace: syncthing
spec:
  selector:
    app: syncthing
  ports:
    - { name: gui, port: 8384, targetPort: 8384 }
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-sync
  namespace: syncthing
spec:
  type: LoadBalancer
  selector:
    app: syncthing
  ports:
    - { name: sync-tcp, port: 22000, targetPort: 22000, protocol: TCP }
    - { name: sync-udp, port: 22000, targetPort: 22000, protocol: UDP }
