apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole@sha256:91dc91ddd413bf461c283204558f8f21839851e9824799075a7ceff7c77eea40
          env:
            - { name: TZ, value: "Etc/UTC" }
            - { name: FTLCONF_dns_listeningMode, value: "all" }
            - name: FTLCONF_misc_dnsmasq_lines
              value: "address=/lab.home.arpa/192.168.1.3"
          ports:
            - { name: dns-tcp, containerPort: 53, protocol: TCP }
            - { name: dns-udp, containerPort: 53, protocol: UDP }
            - { name: http, containerPort: 80 }
          volumeMounts:
            - { name: etc-pihole, mountPath: /etc/pihole }
            - { name: etc-dnsmasq, mountPath: /etc/dnsmasq.d }
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits: { memory: 512Mi }
          securityContext:
            capabilities:
              add: [NET_ADMIN]
          livenessProbe:
            exec:
              command: [dig, "@127.0.0.1", "pi.hole"]
            initialDelaySeconds: 30
      volumes:
        - name: etc-pihole
          persistentVolumeClaim:
            claimName: pihole-etc
        - name: etc-dnsmasq
          persistentVolumeClaim:
            claimName: pihole-dnsmasq
