admin_user: liam
admin_user_comment: "Liam Goodchild (personal admin)"
admin_user_groups: [sudo]

admin_password_hash: "{{ lookup('env', 'LIAM_PASSWORD_HASH') | default('', true) }}"

ssh_password_authentication: true
