DISABLE_LINTERS:
  - TERRAFORM_TFLINT
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TERRAFORM_FMT
  - TERRAFORM_TERRAGRUNT
  - REPOSITORY_CHECKOV
  - REPOSITORY_KICS
  - REPOSITORY_TRIVY
  - REPOSITORY_TRIVY_SBOM
  - REPOSITORY_SYFT
  - REPOSITORY_GRYPE
  - REPOSITORY_SECRETLINT
  - REPOSITORY_TRUFFLEHOG
  - SPELL_CSPELL
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - MARKDOWN_MARKDOWNLINT

SPELL_LYCHEE_FILTER_REGEX_EXCLUDE: "(\\.github/|ansible/|terraform/|docs/rollout-runbook\\.md)"

SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: false
