apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: buildarr
resources:
  - deployment.yaml
configMapGenerator:
  - name: buildarr-config
    files:
      - entrypoint.sh
      - buildarr.yml.tmpl
      - wait-for-dependencies.py
