k3s_version: "v1.36.2+k3s1"
appdata_device: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
appdata_mount: /srv/appdata
media_mount: /mnt/media
media_fs_uuid: bc0c5059-f2ae-4c3a-9822-1781a090b2a8
node_ip: 192.168.1.3
tailscale_authkey: "{{ lookup('env', 'TS_AUTHKEY') }}"
