---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: knowledge-mcp-env
  namespace: knowledge-mcp
spec:
  encryptedData:
    KNOWLEDGE_MCP_BEARER_TOKEN: AgCVcVN5E00vCVwbDrSnWQRDiA51mR2m79YLVadMBvYPxPI9JFbjDMfT7J1IRe+l+Y9Afq+fTsP57NNQn459OPyp92Fqwn5R4WObo+/FitPJyozKvHlGeXV+YYvW9fWjMDEwtEc874vpj+NYJq+Ac5pXQ1vll32ao3KYmNYV0oggCUZpIOlqqqlokAVNJBytjNj/yYgNwFnVgxnnLgtgT1LEnnqjSdzUwVmRgT8R905UukFYEo2Pvx51WbF2z7YaRVl3E1kgxF5Mb49FCHym4qcA2Hkp7YwAzVabZIVVBDKQs9r1XW01sRWmaSBydtpXGARagTFTCSOBotKofV+1NEhVNflpfhCR+BUm4giBrTT0/Oz6gpfVaWybJNDjqzcxIO1LMhLWbSGuXUTwSiL7/fzghpK/JZPT7pGVezTT4uV7pMyuiqRMK+rO80TfxL58/Jmq5yI0FYaTV/Z74S1bZC2iUewkgCMPhJOOnSsN6FSBDTpBtM/cCmOrs9jVRl3h89HOjeagHcDXUwyda+2hq2fVqRSKGuFWrV8zQTYVmVs9vFWaZjU13gI47Xo8qpk/CVuFsyr6cuRiHLK54Qs6Df9ziDVsJX9VZ6vUzufZa942+lBk/Dr45pnZD9N849mCZ0snY6Df4ftfksOB9OD1oAVFDwd8d5Q2gNNxG1qgWA8E6AwT/gR15gKzCSMohtF/N249jP0nR4u0jqcDKLYuM4wAvAlT9dTgB3+sY4tgj1//zIXYpbqPHV3jPRIx5XDAJnJtFaxa9iP5d2Y7hLtyufdP
  template:
    metadata:
      name: knowledge-mcp-env
      namespace: knowledge-mcp
