apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opengym-data
  namespace: opengym
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opengym-media
  namespace: opengym
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
