---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA2wUNqunFIH6JJHvXZ31ltK6K2i0Nw3GU6eu7wyJBqvxOJJer7RB61f9p4pUss50qFzhd1JXphg7csu1HrtP/sHa9uLDkHigOc4wATOU/eVXZwxGOjadZxkbGRApOGeB/QM0PDyKGNkv+AhKamheGSygAgFiORVS7WFRm9yvZ04rDN5SFj22xwL6l3YHjlZ367wy/x1EsGMN1qk44eBCDw94tLirYnuRD9mgOj68RGwp/U4bBafN69I+pPq54Cjcq8SMaCX4JERiRaKqfuyxzLC9dPhwmKxOBmuVqtspl74E9WrLBXNYUDNvu5wXQTyXFrmSTZVgqp2W3YR0Ige0n//LrrVHXCeNKMNb+m59GqRalf456k3bAX9/pApgArJ17dbTV2KsuNDdjKyDvr3L6lCQ9Zu+1SYNVmCwJ9pqnZbSvB4O3X/MTVXsmNWV4mTRqnBwgRKBcjv8vb9/kZWeCAqBzw30t/vfhHYNSylxTZJLWT9DiEAAdvvigCFvTGGeC+Mu7c6gNw4TBGgBfGgdlLOLR8JEFjyk+EyrP0yJgY/YYdvqzaa9bQSlx0j3hRaDl6pj546PeBDRrJfxEAjhQC07pltB0JVwa0aCo2cA0ZGw+RU9YACGeaaYMJLtY9hahcUFk/xKeM2mpFzPDsxHBkuHuy+OvyRTR3/Ttj6sDMzfzJtyYlqdX7OWdW3hX5y00r11OCs11NLE3uXe0GQDFZzRbQlmEav6qgzfkIcRCczYWBJKClvcNPTAGTdnWjWgXWe+VqYQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
