apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: jellyseerr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      containers:
        - name: jellyseerr
          image: ghcr.io/fallenbagel/jellyseerr@sha256:9cc9e9ee6cd5cf5a23feb45c37742ba34cfd6314d81d259cddb373a97ac92cdd
          env:
            - { name: LOG_LEVEL, value: "info" }
            - { name: TZ, value: "Etc/UTC" }
            - { name: PORT, value: "5055" }
          ports:
            - { name: http, containerPort: 5055 }
          volumeMounts:
            - { name: config, mountPath: /app/config }
          readinessProbe:
            httpGet: { path: /api/v1/status, port: 5055 }
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests: { cpu: 100m, memory: 256Mi }
            limits: { memory: 1Gi }
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyseerr-config
