apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      # Old /config ~16M; nominal headroom.
      storage: 1Gi
