---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recyclarr-secrets
  namespace: recyclarr
spec:
  encryptedData:
    SONARR_API_KEY: AgCunQIednjd5orQjCcXcdcF4hLvqA0lAL+Xsqx1AtLeS/+hWKcC3HS6ShxCg6bbdhLWwApUddJYBOYw4qmzs7k2r7Ng6+8JD5lCUUhmyxI2QIAEzpa9RyCfy/of6t9kXsi1tlvL2niNZ4ROhWB29gJaUgeC2zqB9cCXIJhm02EeZUVvyIO8syhMar2ddGPdQgm0VcD6ih2qoBnp2OGZ2Xo64jfwgTQtTlTQuzrGjrprcy/4kBQ6KcJyuGynyLXJ2ClTNcyHVe/qdOyAb6cQQlCUTt7u93SsKPnaTNwzjX962agtYgneeEdGak+6SlrX1wTYODVxLL3JXS3ncNfi2O6fMoOlXHmyrkjcvq6n1SIE21Sp2WQaykq+SVMocBAKpbRAtwMfJkozBvVQDvpyRzNbjyNTJlrkiu4QnPtVkiU8qZD1Ko8ldPl0G5JjkTRN8xYrCZ36HH7o3IuxrThtix2GpuKYLLVH1kL38olt6nTKZ/YzNj6liT2SWnZrgJqpAGyOJi/clK5vvUsez8Itw0P6kpN4pSzCQToDy4rQXAcdeqcg9r2BSFa4NZmG/cmjuyQRIvG7Kp9m2TU0AWfR4w3K3RE1tMi1ZBJ8Fp8VNHr14eq6g6RAoaXAT6BAlw/MV3oz4K+QTHwKWiPF3ZMSW0T8zXvguZI4Vrk+y6Q6+rgLCixCcpDWcsuahRVenfCYRSmjSU5QIv05B3Rfc+An70QhIUUd6a7v+IhDpC7v+jibww==
    RADARR_API_KEY: AgACp/imO2txO9BdAg93XwrDnJWrDjdK1qVO0TXsciWkwJogI8irlnsS9UGQyfj6+RnD60wgzE0a5xw2Xm0LEq1yetnAHDsdaV00pZ6ofIsZcB6SmmpIdaN5H+vGsqCBJMUNrHwly/HDuVKu+I2VYctYQd/9tE3YYtisCFRO7cgRg9eP/A+fwv/6w/YZeR6PycIw7Sg5dzrJp7BbrXXWoCCCXYb1gih1BNUlBMAUBiuseTjX7psu0dq2+DnGhCTTl/jf0ODFhOEi0O3V9iJ7guxQvxmmxQrsE8L+GH/GNusgoMwJEP3Z9iLRcumcbs7atUNXsrfM18LoVFIuk3Yo0d+Cai2Q82M/lTeViugmPjpsRH5Oxn6dgxPqsGKQfFoGU6YOwLlhtpyl5tdv7SUb8RuPbHmpCM/HUiNrls2YOMmvM9G9iZGPg/AHiJvlO47dTcTq7r5yyHpHhyksz7jQB7BB+aIGlS51q3WwObJQwQ+XgqhnUtwnasiwukXI0vpfsIhQlzIR/7i8QLr4/GBjSyLuiNhgODYOFjgBJnOgUFIv8Nje6w3OI2q5VG06xwUPZVdiO5p2wEvDCK9JFKCO7uO997CXLhAck0SAlz3wQRCvQJ52SD6cBiJMh5mLmNkA8TYl87mJF2shZwZVegoW9Yd812y+7FyFDiGQUFCkQMCl+gK50G0g2NX/AFMUCZ/iUeVINnpmMaMSLdtqxjmDme3EYIzZjLwumSL1DaZcn6g6sA==
  template:
    metadata:
      name: recyclarr-secrets
      namespace: recyclarr
    type: Opaque
