---
gha_runner_version: "2.335.1"
gha_runner_sha256: "4ef2f25285f0ae4477f1fe1e346db76d2f3ebf03824e2ddd1973a2819bf6c8cf"

gha_runner_user: ghrunner
gha_runner_group: ghrunner
gha_runner_home: /opt/actions-runner

gha_runner_repo_url: https://github.com/skyhaven-ltd/infra-homelab-config
gha_runner_labels: homelab
gha_runner_name: "{{ inventory_hostname }}"

gha_runner_registration_token: "{{ lookup('env', 'GHA_RUNNER_TOKEN') | default('', true) }}"

gha_runner_packages:
  - acl
  - ca-certificates
  - curl
  - git
  - jq
  - openssh-client
  - python3
  - python3-debian
  - python3-pip
  - python3-venv
  - rsync
  - tar
  - unzip
