apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stockalert
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/skyhaven-ltd/infra-homelab-config.git
    targetRevision: major/kubernetes
    path: kubernetes/apps/stockalert
  destination:
    server: https://kubernetes.default.svc
    namespace: stockalert
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
