---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bookbuddy-env
  namespace: bookbuddy
spec:
  encryptedData:
    WORKER_TOKEN: AgA1Xzb6lAAgnzf8qP59TdP5VqaDdbg6HTrGeMu0FQoYVDRxAsKBzP9tf02YU7jHPtOoV2UaYt9p8+zIjdX90xqNWhBCLVH+s/JC3GgHTRitdoJPNmaZ2CbBOKcqroOkchTiCHKijEXBFGoA2YeBJPogdtS6lpzd79+U6XQ2oAC+P83KAlA3OUxesJ6gJMGZLGZQE/L16KxJ4DlDR7nBLMMur7e8QuLRWx9HEcFFJVIpQekQOWo3JLY6pLyEQeSxgzrHX0qmJGLxAxIXY9y0OMKnoqZ8jQceJrn8L7Wp5xkau2612T48l1lO0VClSRjrWKWWevruwJz0cDCMndSFuDOeGbTSnlGegI1a+z8Vhm99oOC3C5UjoaLr68QhoWYwaPgvk+2fPA+gjWblTSAjNCS8f3lNbGO/QSy//NUcQY/yC+P6K8DmKu0iNKqsTNaX9Ia8ssEHt0deDfuheCQHPkABqXuOWZr9G1nlbDkU3FKP3rXMnMsJLCXzMisPJ2EoznihL03AnQgUG8/dLDmm0BNAKLMTfY9MISI3qugXIo5MySEXrG5FX4IIlTzNh/YFo0vnqrwHMQJ+f6f02B9WeoPkFEAORWl23nMpOoU4irznHmjqW6QEKNdGlPVxpnb5mPlKanrldjZyfIA5tpzgDHAOhZMjm4QDdr+1kLmDjMFtAHhc+jzDuueZgbuS6HgB/aeMpvYesj1cDe2zO4LrgLwjnGp2daDzoD3ExYqzyj9OKmTS38rMLiFYOTLdl8PfzOxuWpaMGztfnb8g6LLnX/1L
  template:
    metadata:
      name: bookbuddy-env
      namespace: bookbuddy
